---
# <% os =  ENV['OS'] || 'debian9' %>
# <% ansible = ENV['ANSIBLE_VERSION'] || '2.7' %>
# <% command = os == 'centos7' ? '/usr/sbin/init' : '/bin/systemd' %>

driver:
  name: docker_cli

transport:
  name: docker_cli

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_chef_for_busser: true
  ansible_verbose: false
  ansible_inventory: ./test/integration/inventory

platforms:
  - name: <%= os %>
    driver_config:
      image: "nishiki/<%= os %>:ansible-<%= ansible %>"
      command: <%= command %>
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      security_opt: seccomp=unconfined
# <% if os == 'debian9' %>
    provisioner:
      extra_vars:
        sensu_repository_system: ubuntu
        sensu_repository_release: xenial
# <% end %>

suites:
  - name: default
