---
driver:
  name: docker_cli

transport:
  name: docker_cli

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_chef_for_busser: true
  ansible_verbose: false
  ansible_inventory: ./test/integration/inventory

platforms:
  - name: debian9
    driver_config:
      image: "nishiki/debian9:ansible-<%= ENV['ANSIBLE_VERSION'] ? ENV['ANSIBLE_VERSION'] : '2.7' %>"
      command: /bin/systemd
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      security_opt: seccomp=unconfined
    provisioner:
      extra_vars:
        sensu_repository_system: ubuntu
        sensu_repository_release: xenial
  - name: ubuntu18.04
    driver_config:
      image: "nishiki/ubuntu18.04:ansible-<%= ENV['ANSIBLE_VERSION'] ? ENV['ANSIBLE_VERSION'] : '2.7' %>"
      command: /bin/systemd
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      security_opt: seccomp=unconfined
  - name: ubuntu16.04
    driver_config:
      image: "nishiki/ubuntu16.04:ansible-<%= ENV['ANSIBLE_VERSION'] ? ENV['ANSIBLE_VERSION'] : '2.7' %>"
      command: /bin/systemd
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      security_opt: seccomp=unconfined

suites:
  - name: default
