---
sudo: required
language: ruby

env:
  - OS=debian9 ANSIBLE_VERSION=2.5
  - OS=debian9 ANSIBLE_VERSION=2.6
  - OS=debian9 ANSIBLE_VERSION=2.7
  - OS=ubuntu18.04 ANSIBLE_VERSION=2.7
  - OS=ubuntu16.04 ANSIBLE_VERSION=2.7
  - OS=centos7 ANSIBLE_VERSION=2.7

services:
  - docker

before_install:
  - bundle install
  - sudo pip install --upgrade pip
  - sudo pip install yamllint
  - sudo pip install ansible-lint
  - git clone https://github.com/ansible/galaxy-lint-rules.git

script:
  - kitchen conv
  - kitchen conv | grep changed=0
  - kitchen verify
  - ansible-lint -r galaxy-lint-rules/rules .
  - yamllint .

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
