---
- name: uninstall bad dependencies
  yum:
    name: '{{ packages }}'
    state: absent
  vars:
    packages:
      - python-urllib3
      - python-requests
  register: result
  retries: 1
  delay: 1
  until: result is success
  tags: sensu

- name: install backend dependencies
  pip:
    name: '{{ packages }}'
  vars:
    packages:
      - urllib3
      - requests
  register: result
  retries: 3
  delay: 1
  until: result is success
  tags: sensu
